name: bip32
description: A BIP32 (https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) compatible library for Flutter writing by Dart.
version: 1.0.5
homepage: https://github.com/anicdh
author: anicdh <anic.dh@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pointycastle:
    git:
      url: https://github.com/jungsoo827/pointycastle.git
      ref: v1.0.2
  hex: ^0.1.2
  bs58check: ^1.0.1

dev_dependencies:
  test: ^1.0.0
#  pointycastle:
#    path: ../pointycastle-jungsoo827
